apiVersion: v1
description: A NodeJS Webapp that showcases how to use Rollout.io feature flags.
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/nodejs.png
name: rollout-app
version: 0.1.0-SNAPSHOT
